apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2026-01-07T23:41:17Z"
  generation: 3
  labels:
    app: web
    version: blue
  name: web-blue
  namespace: ckad-bg-1
  resourceVersion: "16250627"
  uid: 81eb038e-61ef-4d73-9e5f-9994bb5015c3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web-blue
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-blue
    spec:
      containers:
      - args:
        - --text=green
        image: hashicorp/http-echo:1.0
        imagePullPolicy: IfNotPresent
        name: http-echo
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2026-01-08T00:05:28Z"
    lastUpdateTime: "2026-01-08T00:05:28Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-01-08T00:05:28Z"
    lastUpdateTime: "2026-01-08T00:08:22Z"
    message: ReplicaSet "web-blue-694dcfddfd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
